#!/bin/bash
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright 1997-2009 Sun Microsystems, Inc. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common
# Development and Distribution License("CDDL") (collectively, the
# "License"). You may not use this file except in compliance with the
# License. You can obtain a copy of the License at
# http://www.netbeans.org/cddl-gplv2.html
# or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
# specific language governing permissions and limitations under the
# License.  When distributing the software, include this License Header
# Notice in each file and include the License file at
# nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
# particular file as subject to the "Classpath" exception as provided
# by Sun in the GPL Version 2 section of the License file that
# accompanied this code. If applicable, add the following below the
# License Header, with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# Contributor(s):
#
# The Original Software is the DocSup module.
# The Initial Developer of the Original Software is Jan Lahoda.
# Portions created by Jan Lahoda_ are Copyright (C) 2002,2003.
# All Rights Reserved.
#
# If you wish your version of this file to be governed by only the CDDL
# or only the GPL Version 2, indicate your decision by adding
# "[Contributor] elects to include this software in this distribution
# under the [CDDL or GPL Version 2] license." If you do not indicate a
# single choice of license, a recipient has the option to distribute
# your version of this file under either the CDDL, the GPL Version 2 or
# to extend the choice of license to its licensees as provided above.
# However, if you add GPL Version 2 code and therefore, elected the GPL
# Version 2 license, then the option applies only if the new code is
# made subject to such option by the copyright holder.
#
# Contributor(s): Jan Lahoda.
#
NEW_VERSION=1.16
for manifest in `find . -type f -name "manifest.mf"`; do
    mv $manifest $manifest.old
    sed -e "s/OpenIDE-Module-Specification-Version: .*$/OpenIDE-Module-Specification-Version: $NEW_VERSION/" <$manifest.old >$manifest
done;

for properties in `find . -type f -name "project.properties"`; do
    mv $properties $properties.old
    sed -e "s/spec.version.base=.*$/spec.version.base=$NEW_VERSION.0/" <$properties.old >$properties
done;

mv kit/nbproject/project.xml kit/nbproject/project.xml.old
sed -e "s/<specification-version>.*<\/specification-version>/<specification-version>$NEW_VERSION<\/specification-version>/" <kit/nbproject/project.xml.old >kit/nbproject/project.xml
