#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
NEW_VERSION=1.16
for manifest in `find . -type f -name "manifest.mf"`; do
    mv $manifest $manifest.old
    sed -e "s/OpenIDE-Module-Specification-Version: .*$/OpenIDE-Module-Specification-Version: $NEW_VERSION/" <$manifest.old >$manifest
done;

for properties in `find . -type f -name "project.properties"`; do
    mv $properties $properties.old
    sed -e "s/spec.version.base=.*$/spec.version.base=$NEW_VERSION.0/" <$properties.old >$properties
done;

mv kit/nbproject/project.xml kit/nbproject/project.xml.old
sed -e "s/<specification-version>.*<\/specification-version>/<specification-version>$NEW_VERSION<\/specification-version>/" <kit/nbproject/project.xml.old >kit/nbproject/project.xml
