#!/bin/bash -x
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright 2010 Sun Microsystems, Inc. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common
# Development and Distribution License("CDDL") (collectively, the
# "License"). You may not use this file except in compliance with the
# License. You can obtain a copy of the License at
# http://www.netbeans.org/cddl-gplv2.html
# or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
# specific language governing permissions and limitations under the
# License.  When distributing the software, include this License Header
# Notice in each file and include the License file at
# nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
# particular file as subject to the "Classpath" exception as provided
# by Sun in the GPL Version 2 section of the License file that
# accompanied this code. If applicable, add the following below the
# License Header, with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# If you wish your version of this file to be governed by only the CDDL
# or only the GPL Version 2, indicate your decision by adding
# "[Contributor] elects to include this software in this distribution
# under the [CDDL or GPL Version 2] license." If you do not indicate a
# single choice of license, a recipient has the option to distribute
# your version of this file under either the CDDL, the GPL Version 2 or
# to extend the choice of license to its licensees as provided above.
# However, if you add GPL Version 2 code and therefore, elected the GPL
# Version 2 license, then the option applies only if the new code is
# made subject to such option by the copyright holder.
#
# Contributor(s):
#
# Portions Copyrighted 2010 Sun Microsystems, Inc.

. config

if [ "$TOOL_NAME" == "" ] ; then
    echo "tool not specified" >&2
    exit 1;
fi;

TEST_NAME=`basename $0`
BUILD_DIR=`cd ../../../build; pwd`
WORK_DIR=$BUILD_DIR/test/scripted/work/$TEST_NAME
RESULTS_DIR=$BUILD_DIR/test/scripted/results
RESULT_FILE=$RESULTS_DIR/TEST-$TEST_NAME.xml
COMPILER_ZIP=$BUILD_DIR/"$TOOL_NAME".zip

rm -rf $WORK_DIR
mkdir -p $WORK_DIR
mkdir -p `dirname $RESULT_FILE`
cd $WORK_DIR
unzip -q $COMPILER_ZIP

mkdir -p build

create_file() {
    mkdir -p `dirname $1`
    cat >$1 -
}

assert_file_content() {
     DIFF_OUTPUT=`diff $1 - 2>&1`;
     if [ $? != 0 ] ; then
         write_failure_results_file "$DIFF_OUTPUT"
        exit 1;
     fi;
}

fail() {
    write_failure_results_file $1;
}

write_passed_results_file() {
      cat >$RESULT_FILE <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="0" failures="0" hostname="foo" name="$TEST_NAME" tests="1" time="0" timestamp="`date`">
  <properties/>
  <testcase classname="$TEST_NAME" name="main" time="0" />
</testsuite>
EOF
}

write_failure_results_file() {
      ESCAPED_CONTENT=`echo $X | sed -e 's/&/\&amp;/g' | sed -e 's/</\&lt;/g'`;
      cat >$RESULT_FILE <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="0" failures="1" hostname="foo" name="$TEST_NAME" tests="1" time="0" timestamp="`date`">
  <properties/>
  <testcase classname="$TEST_NAME" name="main" time="0">
    <failure message="Test failed" type="junit.framework.AssertionFailedError">$ESCAPED_CONTENT</failure>
  </testcase>
</testsuite>
EOF
}

perform_test;
write_passed_results_file;

exit 0
