#!/bin/bash -x

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


exit 0 #TODO - OverallTest is failing

do_index() {
    rm -rf cache
    mkdir -p cache
    ../../build/indexing-backend/index.sh data Data ../tests/cache/temp.zip integration-data integration-data/example
    (cd cache; unzip temp.zip; rm temp.zip)
}

do_index

OUT=`mktemp`;
trap "rm $OUT" EXIT
JACKPOT_WEB_OPTS=-Xmx128m ../../build/indexing-backend/web.sh --port 0 cache >"$OUT" &

trap "kill %1" EXIT

while [ -z "$PORT" ] ; do
     sleep 1s;
     PORT=`cat "$OUT" | grep "Running on port: " | cut -d ':' -f 2 | tr -d ' '`;
done

(cd integration; mvn -DPORT=$PORT -Dsurefire.timeout=600 test)

exit 0
