#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


perform_test() {
    create_file src/test/Test.java <<EOF
package test;
public class Test {
    private void test() {
        Character.toLowerCase('a');
    }
}
EOF

    create_file src/META-INF/upgrade/test.hint <<EOF
'test':
java.lang.Character.toLowerCase(\$1) :: \$1 instanceof char => java.lang.Character.toUpperCase($1) ;;
EOF

    run_tool src/test/Test.java

    assert_file_content build/META-INF/upgrade/upgrade.diff <<EOF
--- $WORK_DIR/src/test/Test.java
+++ $WORK_DIR/src/test/Test.java
@@ -1,6 +1,6 @@
 package test;
 public class Test {
     private void test() {
-        Character.toLowerCase('a');
+        Character.toUpperCase();
     }
 }
EOF
}

. `dirname $0`/harness
